[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
on_source = 'denops.vim'
hook_add = '''
  nnoremap s<Space> <Cmd>Ddu -name=files file_rec<CR>
  nnoremap / <Cmd>Ddu -name=search line -ui-param-startFilter<CR>
  nnoremap * <Cmd>Ddu -name=search line -input=`expand('<cword>')` -ui-param-startFilter=v:false<CR>
  nnoremap n <Cmd>Ddu -name=search -resume -ui-param-startFilter=v:false<CR>
  nnoremap ;g <Cmd>Ddu -name=search rg -ui-param-ignoreEmpty -source-param-input=`input('Pattern: ')`<CR>
'''
hook_source = '''
  call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sources': [
    \     {'name': 'file_rec'},
    \     {'name': 'line'},
    \     {'name': 'rg'},
    \   ],
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_fzf'],
    \     },
    \   },
    \   'sourceParams': {
    \     'file_rec': {
    \       'ignoredDirectories': ['.git', 'tmp', 'node_modules', 'docker'],
    \      },
    \     'rg': {
    \       'args': ['--column', '--no-heading', '--color', 'never'],
    \      },
    \   },
    \   'filterParams': {
    \     'matcher_fzf': {
    \       'highlightMatched': 'Search',
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \ })
call ddu#custom#patch_local('files', {
    \   'uiParams': {
    \     'ff': {
    \       'split': 'floating',
    \     }
    \   },
    \ })
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'
hook_add = '''
  autocmd FileType ddu-ff call s:ddu_my_settings()
  function! s:ddu_my_settings() abort
    nnoremap <buffer><silent> <CR>    <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
    nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
    nnoremap <buffer><silent> i       <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
    nnoremap <buffer><silent> q       <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  endfunction

  autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
  function! s:ddu_filter_my_settings() abort
    inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
    nnoremap <buffer><silent> <CR> <Cmd>close<CR>
    nnoremap <buffer><silent> q    <Cmd>close<CR>
  endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'
hook_add = '''
  autocmd FileType ddu-filer call s:ddu_my_settings()
  function! s:ddu_my_settings() abort
    nnoremap <buffer> <CR>    <Cmd>call ddu#ui#filer#do_action('itemAction')<CR>
    nnoremap <buffer> <Space> <Cmd>call ddu#ui#filer#do_action('toggleSelectItem')<CR>
    nnoremap <buffer> i       <Cmd>call ddu#ui#filer#do_action('openFilterWindow')<CR>
    nnoremap <buffer> p       <Cmd>call ddu#ui#ff#do_action('preview')<CR>
    nnoremap <buffer> q       <Cmd>call ddu#ui#filer#do_action('quit')<CR>
    nnoremap <buffer> v       <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'open', 'params': {'command': 'vsplit'}})<CR>
  endfunction

  autocmd FileType ddu-filer-filter call s:ddu_filter_my_settings()
  function! s:ddu_filter_my_settings() abort
    inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR>
    nnoremap <buffer><silent> <CR> <Cmd>close<CR>
    nnoremap <buffer><silent> q    <Cmd>close<CR>
  endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
