[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  let g:deoplete#enable_smart_case = 1

  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction

  imap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space() ? "\<TAB>" : deoplete#mappings#manual_complete()
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-d> [denite]

  " grep
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  nnoremap <silent> [denite]<C-g> :<C-u>Denite grep -mode=normal<CR>
  nnoremap <silent> [denite]<C-r> :<C-u>Denite -resume<CR>
  nnoremap <silent> [denite]<C-n> :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  nnoremap <silent> [denite]<C-p> :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>

  " ノーマルモードで起動、jjでノーマルへ
  call denite#custom#option('default', {'mode': 'normal'})
  call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

  " ファイル一覧
  noremap [denite] :Denite file_rec -mode=insert
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('file_rec', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', ['.git/', '__pycache__/', '*.o', '*.make', '*.min.*'])

  " ディレクトリ一覧
  noremap [denite]<C-d> :<C-u>Denite directory_rec<CR>
  noremap [denite]<C-c> :<C-u>Denite directory_rec -default-action=cd<CR>

  " 移動
  call denite#custom#map('normal', 'j', '<denite:nop>', 'noremap')
  call denite#custom#map('normal', 'k', '<denite:nop>', 'noremap')
  call denite#custom#map('normal', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('normal', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
  call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
  call denite#custom#map('normal', '<C-u>', '<denite:move_up_path>', 'noremap')
  call denite#custom#map('insert', '<C-u>', '<denite:move_up_path>', 'noremap')

  " ウィンドウを分割して開く
  call denite#custom#map('normal', '<C-j>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('insert', '<C-j>', '<denite:do_action:split>', 'noremap')
  call denite#custom#map('normal', '<C-l>', '<denite:do_action:vsplit>', 'noremap')
  call denite#custom#map('insert', '<C-l>', '<denite:do_action:vsplit>', 'noremap')
'''
