[[plugins]]
repo = 'yamat47/vim-monokai-pro'
hook_add = '''
let g:monokai_pro#background = "transparent"
colorscheme monokai_pro
set termguicolors
'''

[[plugins]]
repo = 'janko-m/vim-test'
hook_add = '''
function! DockerTransformer(cmd) abort
  if $APP_CONTAINER_NAME != ''
    return 'docker exec -t `docker ps --filter name=$APP_CONTAINER_NAME -q -l` ' . a:cmd
  else
    return a:cmd
  endif
endfunction

let g:test#strategy = 'neovim'
let g:test#custom_transformations = {'docker': function('DockerTransformer')}
let g:test#transformation = 'docker'
let g:test#ruby#bundle_exec = 0
let g:test#ruby#use_spring_binstub = 1

nmap <silent> <C-t><C-n> :TestNearest<CR>
nmap <silent> <C-t><C-f> :TestFile<CR>
nmap <silent> <C-t><C-s> :TestSuite<CR>
nmap <silent> <C-t><C-l> :TestLast<CR>
nmap <silent> <C-t><C-g> :TestVisit<CR>
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tpope/vim-git'
hook_add = '''
let g:gitcommit_cleanup = "scissors"
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR> defx#do_action('open')
  nnoremap <silent><buffer><expr> c defx#do_action('copy')
  nnoremap <silent><buffer><expr> m defx#do_action('move')
  nnoremap <silent><buffer><expr> p defx#do_action('paste')
  nnoremap <silent><buffer><expr> l defx#do_action('open')
  nnoremap <silent><buffer><expr> E defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> P defx#do_action('open', 'pedit')
  nnoremap <silent><buffer><expr> o defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> K defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N defx#do_action('new_file')
  nnoremap <silent><buffer><expr> M defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> C defx#do_action('toggle_columns', 'mark:indent:icon:filename:type:size:time')
  nnoremap <silent><buffer><expr> S defx#do_action('toggle_sort', 'time')
  nnoremap <silent><buffer><expr> d defx#do_action('remove')
  nnoremap <silent><buffer><expr> r defx#do_action('rename')
  nnoremap <silent><buffer><expr> ! defx#do_action('execute_command')
  nnoremap <silent><buffer><expr> x defx#do_action('execute_system')
  nnoremap <silent><buffer><expr> yy defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> . defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> ; defx#do_action('repeat')
  nnoremap <silent><buffer><expr> h defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> ~ defx#do_action('cd')
  nnoremap <silent><buffer><expr> q defx#do_action('quit')
  nnoremap <silent><buffer><expr> <Space> defx#do_action('toggle_select') . 'j'
  nnoremap <silent><buffer><expr> * defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> j line('.') == line('$') ? 'gg' : 'j'
  nnoremap <silent><buffer><expr> k line('.') == 1 ? 'G' : 'k'
  nnoremap <silent><buffer><expr> <C-l> defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <C-g> defx#do_action('print')
  nnoremap <silent><buffer><expr> cd defx#do_action('change_vim_cwd')
endfunction

call defx#custom#option('_', {'show_ignored_files': 1})

nmap <silent> <C-d><C-f> :<C-u>Defx<CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
let g:deol#shell_history_path = '~/.zsh_history'

nnoremap <silent> <C-d><C-o> :<C-u>Deol -split=vertical<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>    denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d       denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p       denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q       denite#do_map('quit')
  nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space> denite#do_map('toggle_select').'j'
endfunction

" Change file/rec command.
call denite#custom#var('file/rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

" Ag command on grep source
call denite#custom#var('grep', 'command',        ['ag'])
call denite#custom#var('grep', 'default_opts',   ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt',    [])
call denite#custom#var('grep', 'separator',      ['--'])
call denite#custom#var('grep', 'final_opts',     [])

" Change ignore_globs
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', [ '.git/', '*.css' ])

" Key mapping
nmap <silent> <C-d><C-g> :<C-u>Denite grep -split=floating<CR>
nmap <silent> <C-d><C-]> :<C-u>DeniteCursorWord grep -split=floating<CR>
nmap <silent> <C-d><C-l> :<C-u>Denite file/rec -split=floating file:new<CR>
nmap <silent> <C-d><C-r> :<C-u>Denite -resume<CR>
nmap <silent> <C-d><C-n> :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
nmap <silent> <C-d><C-p> :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>

augroup transparent-windows
  autocmd!
  autocmd FileType denite set winblend=50
  autocmd FileType denite-filter set winblend=50
augroup END
'''
